### ISSUE TITLE
Need to mention functions that return promises

### ISSUE THREAD

**Issue by jfriend00** [aycangulez/fn-one#1]
Your one page doc should mention that the functions you pass it can return a promise, what will happen if they reject and what happens with their resolved value.  I had to look at the code to see that this even supported promise-returning function since that isn't mentioned anywhere in your description.

**Comment by aycangulez** [comment]
Thank you for your feedback. Updated the documentation. Please let me know what you think.

**Comment by aycangulez** [comment]
Marking as resolved.

**Comment by aycangulez** [comment]
Marking as resolved.
